name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js, NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci
      - run: npm run build
      - run: dir dist

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ".\\dist\\*.appx"
